config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'uploads/create'
  get 'uploads/destroy'

  # homes
  root 'homes#top'
  get  'about', to: 'homes#about'
  get  'convention', to: 'homes#convention'
  get  'update', to: 'homes#update'

  # users
  devise_for :users
  resources  :users, except: [:destroy] do
    member do
      get :followed, :followers
    end
    resources :relationships, only: %i[create destroy]
  end
  # user論理削除
  put '/users/:id/hide', to: 'users#hide', as: 'users_hide'

  # plots
  resources :plots do
    resources :comments, only: %i[create update destroy]
    resource  :likes,    only: %i[create destroy]
  end
  resources :uploads, only: %i[create destroy]

  # tags
  resources :tags, only: %i[index show search]

  # searchs
  get '/search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :plot

  # バリデーション
  # コメントは1～140文字まで、空はダメ
  validates :content, presence: true, length: { minimum: 1, maximum: 140 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :plot
  validates_uniqueness_of :plot_id, scope: :user_id
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :user
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  # バリデーション
  # titleは1～50文字までで同一・空はダメ
  validates :title, presence: true, uniqueness: true, length: { minimum: 1, maximum: 50 }
  # bodyは空はダメ、summernoteのタグが入ってしまうため最小は5
  validates :body, presence: true, length: { minimum: 5 }

  # タグの作成・更新に使用します
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name)unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    # 古いタグの削除
    old_tags.each do |old|
      self.tags.delete tags.find_by(tag_name: old)
    end

    # 新しいタグの生成
    new_tags.each do |new|
      new_plot_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_plot_tag
    end
  end

  # すでにlikeしたかどうかの判定（like unlikeの切り替え）
  def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :plots, through: :tagmaps

  # バリデーション
  # tag_nameは1～20文字、空はダメ
  validates :tag_name, presence: true, length: { minimum: 1,  maximum: 20 }
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :plot
  belongs_to :tag
  validates :plot_id, presence: true
  validates :tag_id, presence: true
end

app/models/upload.rb
class Upload < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :icon
  has_many :plots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_plots, through: :likes, source: :plot
  has_many :comments, dependent: :destroy

  # follower/followed
  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships

  # バリデーション
  # nameは1～20文字までで同一・空はダメ
  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }
  # introduction200文字まで
  validates :introduction, length: { maximum: 200 }

  def active_for_authentication?
    super && (self.is_deleted == false )
  end

  def followed?(user)
    followed_relationships.find_by(followed_id: user.id)
  end

  def follow(user)
    followed_relationships.create!(followed_id: user.id)
  end

  def unfollow(user)
    followed_relationships.find_by(followed_id: user.id).destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @plot = Plot.find(params[:plot_id])
    @comment = @plot.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render 'index'
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render 'index'
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :plot_id, :user_id, :star)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @all_ranks = Plot.find(Like.group(:plot_id).order('count(plot_id)desc').limit(3).pluck(:plot_id))
  end

  def about
  end

  def convention
  end

  def update
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @plot = Plot.find(params[:plot_id])
    like = @plot.likes.new(user_id: current_user.id)
    like.save
  end

  def destroy
    @plot = Plot.find(params[:plot_id])
    like = @plot.likes.find_by(user_id: current_user.id)
    like.destroy
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag_list = Tag.all
  end

  def show
    @tag_list = Tag.all
    @tag = Tag.find(params[:id])
    @plots = @tag.plots.page(params[:page])
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @plots = @tag.plots.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [plot, comment], url: plot_comments_path(@plot) ) do |f| %>
<div class="row">
  <div class="col form-group">
    <%= f.text_area :content, class: "input-mysize form-control", placeholder: "コメントを入力..." %>
  </div>
</div>
<div class="row">
  <div class="col form-group" id="star" data-turbolinks='false'>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
</div>
<div class="row">
  <div class="col-5 form-group">
    <%= f.submit "送信", class: "btn btn-block btn-primary comment-submit float-right" %>
  </div>
</div>
<script>
  $('#star').empty();
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    scoreName: 'comment[star]',
    half: false,
  });
</script>
<% end %>

app/views/comments/_index.html.erb
<div id="accordion" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          コメント（<%= comments.count %>）
        </a>
      </h5>
    </div>
    <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-body" id="commnet_area">
        <table class="table table-hover">
          <thead>
            <tr>
              <th></th>
              <th>ユーザー名</th>
              <th>コメント</th>
              <th>評価</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% comments.each do |comment| %>
          <% unless comment.id.nil? %>
          <tbody>
            <tr>
              <th class="comment-avatar">
                <%= attachment_image_tag comment.user, :icon, fallback: "no_image.png", class:"comment-image", size: "40x40" %>
              </th>
              <th class="comment-text">
                <%= link_to "@#{comment.user.name}", user_path(comment.user.id) %>
              </th>
              <th class="comment-entry"><%= comment.content %></th>
              <th id="star-rate<%= comment.id %>" data-turbolinks='false'></th>
                <script>
                  $('#star-rate<%= comment.id %>').empty();
                  $('#star-rate<%= comment.id %>').raty({
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    half      : false,
                    readOnly  : true,
                    score     : <%= comment.star %>,
                  });
                </script>
              <th class="comment-entry">
              <% if comment.user == current_user %>
                <%= link_to plot_comment_path(comment.plot.id, comment.id), method: :delete, class: "comment_destroy", remote: true do %>
                  <i class="fas fa-trash" style="color: black;"></i>
                <% end %>
              <% end %>
              </th>
              <th class="comment-date"><%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></th>
            </tr>
          </tbody>
          <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.js.erb
$("#comment_area").html("<%= j(render 'index', { comments: @comment.plot.comments }) %>");
$("textarea").val('');
$('#star').empty('');
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  scoreName: 'comment[star]',
  half: false,
});