config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'uploads/create'
  get 'uploads/destroy'

  # homes
  root 'homes#top'
  get  'about', to: 'homes#about'
  get  'convention', to: 'homes#convention'
  get  'update', to: 'homes#update'

  # users
  devise_for :users
  resources  :users, except: [:destroy] do
    member do
      get :followed, :followers
    end
    resources :relationships, only: %i[create destroy]
  end
  # user論理削除
  put '/users/:id/hide', to: 'users#hide', as: 'users_hide'

  # plots
  resources :plots do
    resources :comments, only: %i[create update destroy]
    resource  :likes,    only: %i[create destroy]
  end
  resources :uploads, only: %i[create destroy]

  # tags
  resources :tags, only: %i[index show search]

  # searchs
  get '/search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :plot

  # バリデーション
  # コメントは1～140文字まで、空はダメ
  validates :content, presence: true, length: { minimum: 1, maximum: 140 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :plot
  validates_uniqueness_of :plot_id, scope: :user_id
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :user
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  # バリデーション
  # titleは1～50文字までで同一・空はダメ
  validates :title, presence: true, uniqueness: true, length: { minimum: 1, maximum: 50 }
  # bodyは空はダメ、summernoteのタグが入ってしまうため最小は5
  validates :body, presence: true, length: { minimum: 5 }

  # タグの作成・更新に使用します
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name)unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    # 古いタグの削除
    old_tags.each do |old|
      self.tags.delete tags.find_by(tag_name: old)
    end

    # 新しいタグの生成
    new_tags.each do |new|
      new_plot_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_plot_tag
    end
  end

  # すでにlikeしたかどうかの判定（like unlikeの切り替え）
  def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :plots, through: :tagmaps

  # バリデーション
  # tag_nameは1～20文字、空はダメ
  validates :tag_name, presence: true, length: { minimum: 1,  maximum: 20 }
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :plot
  belongs_to :tag
  validates :plot_id, presence: true
  validates :tag_id, presence: true
end

app/models/upload.rb
class Upload < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :icon
  has_many :plots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_plots, through: :likes, source: :plot
  has_many :comments, dependent: :destroy

  # follower/followed
  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships

  # バリデーション
  # nameは1～20文字までで同一・空はダメ
  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }
  # introduction200文字まで
  validates :introduction, length: { maximum: 200 }

  def active_for_authentication?
    super && (self.is_deleted == false )
  end

  def followed?(user)
    followed_relationships.find_by(followed_id: user.id)
  end

  def follow(user)
    followed_relationships.create!(followed_id: user.id)
  end

  def unfollow(user)
    followed_relationships.find_by(followed_id: user.id).destroy
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag_list = Tag.all
  end

  def show
    @tag_list = Tag.all
    @tag = Tag.find(params[:id])
    @plots = @tag.plots.page(params[:page])
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @plots = @tag.plots.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/nav/_menu-l.html.erb
<ul class="navbar-nav">
  <% if user_signed_in? %>
    <li>
      <%= link_to " プロットを見る", plots_path, class: 'nav-link text-light fas fa-book-reader' %>
    </li>
    <li>
      <%= link_to " ユーザーを見る", users_path, class: 'nav-link text-light fas fa-users' %>
    </li>
    <li>
      <%= link_to " タグ一覧を見る", tags_path, class: 'nav-link text-light fas fa-tags' %>
    </li>
  <% else %>
    <li>
      <%= link_to " このサイトについて", about_path, class: 'nav-link text-light fas fa-info-circle'%>
    </li>
    <li>
      <%= link_to " 利用規約", convention_path, class: 'nav-link text-light fas fab fa-readme' %>
    </li>
  <% end %>
</ul>

app/views/layouts/nav/_menu-r.html.erb
<ul class="navbar-nav ml-auto">
  <% if user_signed_in? %>
    <%# ログイン中はこちらを表示 %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ようこそ <%= current_user.name %> さん
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to " マイページ", user_path(current_user.id), class: 'dropdown-item fas fa-user' %>
        <%= link_to " プロットを書く", new_plot_path, class: 'dropdown-item fas fa-book-open' %>
        <%= link_to " 利用規約", convention_path, class: 'dropdown-item fas fab fa-readme' %>
        <%= link_to " 更新情報", update_path, class: 'dropdown-item fas fa-history' %>
        <div class="dropdown-divider"></div>    <%# 仕切り %>
        <%= link_to " ログアウト", destroy_user_session_path, class: 'dropdown-item fas fa-sign-out-alt', method: :delete  %>
      </div>
    </li>
  <% else %>
    <%# ログアウト中はこちらを表示 %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ようこそ ゲスト さん
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to " 新規登録する", new_user_registration_path, class: 'dropdown-item  fas fa-user-plus' %>
        <%= link_to " ログインする", new_user_session_path, class: 'dropdown-item  fas fa-sign-in-alt' %>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/nav/_search.html.erb
<div class="form-inline ml-auto" role="form">
  <%= form_with url:search_path, method: :get, local: true do |f| %>
    <form class="form-inline">
      <div class="form-group">
        <div>
          <%= f.text_field 'search[value]', class: 'form-control' %>
        </div>
        <div class="ml-2">
          <%= f.select 'search[model]', options_for_select({ "ユーザー" => "user", "プロット" => "plot" }), {}, class: 'form-control' %>
        </div>
        <div class="ml-2">
          <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }), {}, class: 'form-control' %>
        </div>
        <div class="ml-2">
          <%= f.submit :"検索", class: 'btn btn-success' %>
        </div>
      </div>
    </form>
  <% end %>
</div>