config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'uploads/create'
  get 'uploads/destroy'

  # homes
  root 'homes#top'
  get  'about', to: 'homes#about'
  get  'convention', to: 'homes#convention'
  get  'update', to: 'homes#update'

  # users
  devise_for :users
  resources  :users, except: [:destroy] do
    member do
      get :followed, :followers
    end
    resources :relationships, only: %i[create destroy]
  end
  # user論理削除
  put '/users/:id/hide', to: 'users#hide', as: 'users_hide'

  # plots
  resources :plots do
    resources :comments, only: %i[create update destroy]
    resource  :likes,    only: %i[create destroy]
  end
  resources :uploads, only: %i[create destroy]

  # tags
  resources :tags, only: %i[index show search]

  # searchs
  get '/search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :plot

  # バリデーション
  # コメントは1～140文字まで、空はダメ
  validates :content, presence: true, length: { minimum: 1, maximum: 140 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :plot
  validates_uniqueness_of :plot_id, scope: :user_id
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :user
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  # バリデーション
  # titleは1～50文字までで同一・空はダメ
  validates :title, presence: true, uniqueness: true, length: { minimum: 1, maximum: 50 }
  # bodyは空はダメ、summernoteのタグが入ってしまうため最小は5
  validates :body, presence: true, length: { minimum: 5 }

  # タグの作成・更新に使用します
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name)unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    # 古いタグの削除
    old_tags.each do |old|
      self.tags.delete tags.find_by(tag_name: old)
    end

    # 新しいタグの生成
    new_tags.each do |new|
      new_plot_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_plot_tag
    end
  end

  # すでにlikeしたかどうかの判定（like unlikeの切り替え）
  def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :plots, through: :tagmaps

  # バリデーション
  # tag_nameは1～20文字、空はダメ
  validates :tag_name, presence: true, length: { minimum: 1,  maximum: 20 }
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :plot
  belongs_to :tag
  validates :plot_id, presence: true
  validates :tag_id, presence: true
end

app/models/upload.rb
class Upload < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :icon
  has_many :plots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_plots, through: :likes, source: :plot
  has_many :comments, dependent: :destroy

  # follower/followed
  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships

  # バリデーション
  # nameは1～20文字までで同一・空はダメ
  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }
  # introduction200文字まで
  validates :introduction, length: { maximum: 200 }

  def active_for_authentication?
    super && (self.is_deleted == false )
  end

  def followed?(user)
    followed_relationships.find_by(followed_id: user.id)
  end

  def follow(user)
    followed_relationships.create!(followed_id: user.id)
  end

  def unfollow(user)
    followed_relationships.find_by(followed_id: user.id).destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @all_ranks = Plot.find(Like.group(:plot_id).order('count(plot_id)desc').limit(3).pluck(:plot_id))
  end

  def about
  end

  def convention
  end

  def update
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @plot = Plot.find(params[:plot_id])
    like = @plot.likes.new(user_id: current_user.id)
    like.save
  end

  def destroy
    @plot = Plot.find(params[:plot_id])
    like = @plot.likes.find_by(user_id: current_user.id)
    like.destroy
  end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_check, only: %i[edit destroy update]

  def index
    @plots = Plot.page(params[:page])
    @tag_list = Tag.all
    @plot = current_user.plots.new
  end

  def show
    @plot = Plot.find(params[:id])
    @user = @plot.user
    @plot_tags = @plot.tags
    @comment = Comment.new
    @comments = @plot.comments.order(created_at: :desc)
  end

  def new
    @plot = Plot.new
  end

  def create
    @plot = Plot.new(plot_params)
    @plot.user_id = current_user.id
    tag_list = params[:plot][:tag_name].split(nil)
    if @plot.save
      @plot.save_tag(tag_list)
      redirect_to plot_path(@plot)
      flash[:notice] = '作品を投稿しました'
    else
      render 'new'
    end
  end

  def edit
    @plot = Plot.find(params[:id])
    @plot_tags = @plot.tags.pluck(:tag_name).split(nil)
  end

  def update
    @plot = Plot.find(params[:id])
    @plot.update(plot_params)
    tag_list = params[:plot][:tag_name].split(nil)
    if @plot.update_attributes(plot_params)
      @plot.save_tag(tag_list)
      redirect_to plot_path(@plot.id)
      flash[:notice] = '作品の編集に成功しました'
    else
      render 'edit'
    end
  end

  def destroy
    @plot = Plot.find(params[:id])
    if @plot.destroy
      redirect_to plots_path
      flash[:notice] = '投稿を削除しました'
    else
      render 'show'
    end
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @plots = @tag.plots.all
  end

  private

  def plot_params
    params.require(:plot).permit(:title, :body)
  end

  # 実行者＝投稿者であることを確認して編集・削除を許可
  def user_check
    unless Plot.find(params[:id]).user.id.to_i == current_user.id
      redirect_to plots_path
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag_list = Tag.all
  end

  def show
    @tag_list = Tag.all
    @tag = Tag.find(params[:id])
    @plots = @tag.plots.page(params[:page])
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @plots = @tag.plots.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<div class="row">
  <div class="col-3 d-flex flex-wrap align-content-center">
    <% if plot.liked_by?(current_user) %>
      <%= link_to plot.likes.count, plot_likes_path(plot.id), method: :delete, class: "fas fa-heart heart_red", remote: true %>
    <% else %>
      <%= link_to plot.likes.count, plot_likes_path(plot.id), method: :post, class: "fas fa-heart heart_blue", remote: true %>
    <% end %>
  </div>
</div>

app/views/likes/create.js.erb
$('#likes_<%= @plot.id %>').html("<%= j(render partial: 'likes/like', locals: {plot: @plot}) %>");

app/views/likes/destroy.js.erb
$('#likes_<%= @plot.id %>').html("<%= j(render partial: 'likes/like', locals: {plot: @plot}) %>");

app/views/plots/_error.html.erb
<%# エラーアラート表示 %>
<% if plot.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">投稿に失敗しました</h4>
  <% plot.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</div>
<% end %>

app/views/plots/edit.html.erb
<%= render 'error', plot: @plot %>
<h1 class="title">新しいプロットの作成</h1>
<%= form_with model: @plot, local: true do |f| %>
<div class="row mt-3">
  <div class="col-5 field">
    <label class="form-group">タイトル</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="col-5 field">
    <label class="form-group">タグ（スペースで複数設定できます）</label>
      <%= f.text_field :tag_name, value: @plot_tags, class: 'form-control' %>
  </div>
  <div class="col-2 field">
    <%= link_to '編集をキャンセル', plot_path(@plot.id), class: 'btn-block btn btn-outline-primary' %>
    <%= f.submit " 投稿を確定する", class: 'btn-block btn btn-success' %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 field">
    <label class="form-group">本文</label>
    <%= f.text_area :body, 'data-provider': :summernote %>
  </div>
</div>
<% end %>

app/views/plots/index.html.erb
<h1 class="title">投稿作品</h1>
<h4>いい作品には「いいね！」をつけて応援できます！</h4>
<%= render 'plots/indexpage/body', plots: @plots %>

app/views/plots/indexpage/_body.html.erb
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>タイトル</th>
      <th>ユーザー名</th>
      <th>いいね！</th>
      <th>投稿日時</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% plots.each do |plot| %>
    <tr>
      <th scope="row">
        <%= plot.title %>
      </th>
      <td>
        <%= plot.user.name %>
      </td>
      <td id="likes_<%= plot.id %>">
        <% if plot.liked_by?(current_user) %>
          <%= link_to plot.likes.count, plot_likes_path(plot.id), method: :delete, class: "fas fa-heart heart_red", remote: true %>
        <% else %>
          <%= link_to plot.likes.count, plot_likes_path(plot.id), method: :post, class: "fas fa-heart heart_blue", remote: true %>
        <% end %>
      </td>
      <td>
        <%= plot.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      </td>
      <td>
        <%= link_to '作品を読む', plot_path(plot.id), class: 'btn btn-success' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate plots %>

app/views/plots/new.html.erb
<%= render 'error', plot: @plot %>
<h1 class="title">新しいプロットの作成</h1>
<%= form_with model: @plot, local: true do |f| %>
<div class="row mt-3">
  <div class="col-5 field">
    <label class="form-group">タイトル</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="col-5 field">
    <label class="form-group">タグ（スペースで複数設定できます）</label>
    <%= f.text_field :tag_name, class: 'form-control' %>
  </div>
  <div class="col-2 field">
    <%= link_to '投稿をキャンセル', plots_path, class: 'btn-block btn btn-outline-primary' %>
    <%= f.submit " 投稿を確定する", class: 'btn-block btn btn-success' %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 field">
    <label class="form-group">本文</label>
    <%= f.text_area :body, 'data-provider': :summernote %>
  </div>
</div>
<% end %>

app/views/plots/search.html.erb
<%# タグのリンクをクリックしたらそのタグの記事だけがずらっと出るようにしたい %>

<% @tag_list.each do |list| %>
  <%= "(#{list.plots.count})" %>
<% end %>
<br>
<%= "#{@tag.tag_name}" %>
<br>
<% @plots.each do |plot| %>
  <%= link_to plot.title, plot_path(plot.id) %>
<% end %>
<br>
<%= link_to 'home', root_path %>

app/views/plots/show.html.erb
<%= render 'plots/showpage/body', plot: @plot %>
<hr>
<%= render 'plots/showpage/info', plot: @plot %>
<hr>
<div class="row">
  <div class="col-8" id="comment_area">
    <%= render partial: 'comments/index', locals: { comments: @comments } %>
  </div>
  <div class="col-4 comment-create">
    <% if user_signed_in? %>
      <%= render partial: 'comments/form', locals: { comment: @comment, plot: @plot } %>
    <% end %>
  </div>
</div>
<div class="row d-flex justify-content-center">
  <div class="col-6 btn-group" role="group" aria-label="Basic example">
    <%= link_to '一覧に戻る', plots_path, class: 'btn btn-outline-primary' %>
    <% if user_signed_in? && @user.id == current_user.id %>
      <%= link_to '投稿の編集', edit_plot_path, class: 'btn btn-outline-primary' %>
      <%= link_to '投稿を削除', plot_path, class: 'btn btn-outline-primary', method: :delete %>
    <% else %>
      <%= link_to 'ユーザーページへ', user_path(@user.id), class: 'btn btn-outline-primary' %>
    <% end %>
  </div>
</div>

app/views/plots/showpage/_body.html.erb
<div class="row mt-5">
  <div class="col-8 offset-2">
    <h1 class="title"><%= plot.title %></h1>
  </div>
  <div class="col-2">
    <p>
      <%= link_to 'https://creativecommons.org/licenses/by/4.0/deed.ja' do %>
        <%= image_tag asset_path('by.png') %>
      <% end %>
    </p>
  </div>
</div>
<div class="row mt-5">
  <div class="col-8 offset-2">
    <%== plot.body %>
  </div>
  <div class="col-2"></div>
</div>
<div class="row mt-3">
  <div class="col-8 offset-2">
    <h5>登録されたタグ</h5>
    <% @plot_tags.each do |tag| %>
      <%= link_to tag.tag_name, tag_path(tag.id), class: 'btn btn-sm btn-outline-secondary' %>
      <%= "(#{tag.plots.count})" %>
    <% end %>
  </div>
  <div class="col-2"></div>
</div>

app/views/plots/showpage/_info.html.erb
<div class="row">
  <div class="col-6">
    <div class="media">
      <%= attachment_image_tag plot.user, :icon, size: '150x150', fallback: 'no_image.png', class: 'img-thumbnail' %>
      <div class="media-body">
        <h4 class="mt-0 ml-3"><%= plot.user.name %></h4>
        <p class="mt-2 ml-3"><%= plot.user.introduction %></p>
      </div>
    </div>
  </div>
  <div class="col-5 offset-1 d-flex flex-wrap align-content-center">
    <div id="likes_<%= @plot.id %>">
      <%= render partial: 'likes/like', locals: { plot: @plot } %>
    </div>
  </div>
</div>

app/views/tags/_tags.html.erb
<div class="row mt-3">
  <% tag_list.each do |list| %>
    <div class="mr-3">
      <%= link_to list.tag_name, tag_path(list.id), class: 'btn btn-sm btn-outline-secondary' %>
      <%= "(#{list.plots.count})" %>
    </div>
  <% end %>
</div>

app/views/tags/index.html.erb
<h1 class="title">タグ</h1>
<h4>タグからお気に入りのプロットを探そう！</h4>
<%= render 'tags', tag_list: @tag_list %>

app/views/tags/show.html.erb
<h1 class="title">タグ：<%= "#{@tag.tag_name}" %></h1>
<h4>このタグは <%= @tag.plots.count %> 件登録されています</h4>
<%= render 'plots/indexpage/body', plots: @plots %>
<%# 他のタグを表示しておく %>
<div class="row">
  <div class="col">
    <p>他のタグを見る</p>
    <%= render 'tags', tag_list: @tag_list %>
  </div>
</div>