config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'uploads/create'
  get 'uploads/destroy'

  # homes
  root 'homes#top'
  get  'about', to: 'homes#about'
  get  'convention', to: 'homes#convention'
  get  'update', to: 'homes#update'

  # users
  devise_for :users
  resources  :users, except: [:destroy] do
    member do
      get :followed, :followers
    end
    resources :relationships, only: %i[create destroy]
  end
  # user論理削除
  put '/users/:id/hide', to: 'users#hide', as: 'users_hide'

  # plots
  resources :plots do
    resources :comments, only: %i[create update destroy]
    resource  :likes,    only: %i[create destroy]
  end
  resources :uploads, only: %i[create destroy]

  # tags
  resources :tags, only: %i[index show search]

  # searchs
  get '/search', to: 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :icon
  has_many :plots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_plots, through: :likes, source: :plot
  has_many :comments, dependent: :destroy

  # follower/followed
  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships

  # バリデーション
  # nameは1～20文字までで同一・空はダメ
  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }
  # introduction200文字まで
  validates :introduction, length: { maximum: 200 }

  def active_for_authentication?
    super && (self.is_deleted == false )
  end

  def followed?(user)
    followed_relationships.find_by(followed_id: user.id)
  end

  def follow(user)
    followed_relationships.create!(followed_id: user.id)
  end

  def unfollow(user)
    followed_relationships.find_by(followed_id: user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = '退会済みです。'
        redirect_to new_user_session_path
      end
    else
      flash[:error] = '必須項目を入力してください。'
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @plot = Plot.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
      flash[:notice] = 'プロフィールの変更に成功しました'
    else
      render 'edit'
    end
  end

  def hide
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :icon)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error.html.erb
<%# エラーアラート表示 %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">保存に失敗しました</h4>
  <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</div>

app/views/users/_info.html.erb
<div class="row">
  <div class="col-2">
    <%= attachment_image_tag user, :icon, size: '150x150', fallback: 'no_image.png', class: 'img-thumbnail' %>
  </div>
  <div class="col-6 d-flex flex-column">
    <h2 class="p-2"><%= user.name %></h2>
    <h5 class="p-2">Biography</h5>
    <h6 class="p-2"><%= user.introduction %></h6>
  </div>
  <div class="col-2">
    <div class="row">
    <% if user_signed_in? && user.id == current_user.id %>
      <%= link_to ' プロフィール編集', edit_user_path, class: 'fas fa-user-edit btn-block btn btn-secondary' %>
    <% else %>
      <%= render partial: "relationships/follow_form", locals: { user: @user } %>
    <% end %>
    </div>
    <div class="row mt-2">
      <%= link_to " プロットを書く！", new_plot_path, class: 'fas fa-book-open btn-block btn btn-success' %>
    </div>
  </div>
</div>

app/views/users/_like.html.erb
<div class="row">
  <div class="col-6">
    <h1 class="title">いいね！</h1>
  </div>
  <div class="col-6 d-flex flex-wrap align-content-center">
    <h5><%= user.name %>さんは <%= user.likes.count %> 回いいね！しています</h5>
  </div>
</div>
<table class="table table-hover mt-3">
  <thead class="thead-dark">
    <tr>
      <th></th>
      <th>ユーザー名</th>
      <th>タイトル</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% user.liked_plots.each do |plot| %>
    <tr>
      <th scope="row">
        <%= attachment_image_tag( user, :icon, size: '80x80', fallback: 'no_image.png') %>
      </th>
      <td><%= plot.user.name %></td>
      <td><%= plot.title %></td>
      <td>
        <%= link_to '作品を読む', plot_path(plot.id), class: 'btn btn-success' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/_plot.html.erb
<div class="row">
  <div class="col-6">
    <h1 class="title">投稿作品</h1>
  </div>
  <div class="col-6 d-flex flex-wrap align-content-center">
    <h5><%= user.name %>さんは <%= user.plots.count %> 個の投稿をしています</h5>
  </div>
</div>
<table class="table table-hover mt-3">
  <thead class="thead-dark">
    <tr>
      <th>タイトル</th>
      <th>いいね数</th>
      <th>投稿日時</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% user.plots.each do |plot| %>
    <tr>
      <th scope="row">
        <%= plot.title %>
      </th>
      <td>
        <%= plot.likes.count %> いいね
      </td>
      <td>
        <%= plot.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      </td>
      <td>
        <%= link_to '作品を読む', plot_path(plot.id), class: 'btn btn-success' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= render 'error', user: @user %>
<% end %>
<h1 class="title">プロフィール編集</h1>
<%= form_with model: @user, local: true do |f| %>
<div class="row">
  <div class="col-2">
    <%= attachment_image_tag @user, :icon, size: '100x100', fallback: 'no_image.png', class: 'img-thumbnail' %>
  </div>
  <div class="col-4">
    <div class="card">
      <label class="card-title">プロフィール画像の変更</label>
      <%= f.attachment_field :icon, class: 'card-body' %>
    </div>
  </div>
  <div class="col-2 offset-4">
    <% if user_signed_in? && @user.id == current_user.id %>
      <%= link_to ' 退会する', users_hide_path(current_user), method: :put, data: { confirm: "本当に退会しますか？\n退会するとログインができなくなります" }, class: "fas fa-minus-circle btn-block btn btn-danger" %>
    <% end %>
  </div>
</div>
<div class="row mt-2">
  <div class="col-3">
    <label class="form-group">ユーザー名</label>
    <%= f.text_field :name, autofocus: true, id: "inputName, focusedInput", placeholder: "name", class: 'form-control' %>
  </div>
</div>
<div class="row mt-2">
  <div class="col-5">
    <label class="form-group">Biography</label>
    <%= f.text_area :introduction, placeholder: '自己紹介...', class: 'form-control' %>
  </div>
</div>
<div class="row mt-2">
  <div class="col-3">
    <%= f.submit "編集を完了する", class: 'btn btn-success' %>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1 class="title">ユーザー</h1>
<h4>あなたイチオシのクリエイターを見つけよう！</h4>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th></th>
      <th>ユーザー名</th>
      <th>イントロダクション</th>
      <th>フォロワー数</th>
      <th></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <th scope="row">
        <%= link_to user_path(user.id) do %>
          <%= attachment_image_tag user, :icon, size: '50x50', fallback: 'no_image.png' %>
        <% end %>
      </th>
      <td><%= user.name %></td>
      <td><%= user.introduction %></td>
      <td><%= user.followers.count %> フォロワー</td>
      <td><%= link_to 'ユーザーページを見る', user_path(user.id), class: 'btn btn-success' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/users/show.html.erb
<div class="d-flex flex-column mb-3">
  <%= render 'info', user: @user %>
</div>
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="item1-tab" data-toggle="tab" href="#item1" role="tab" aria-controls="item1" aria-selected="true">投稿作品</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="item2-tab" data-toggle="tab" href="#item2" role="tab" aria-controls="item2" aria-selected="false">いいねした作品</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="item3-tab" data-toggle="tab" href="#item3" role="tab" aria-controls="item3" aria-selected="false">フォロ中ー</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="item4-tab" data-toggle="tab" href="#item4" role="tab" aria-controls="item4" aria-selected="false">フォロワー</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade show active" id="item1" role="tabpanel" aria-labelledby="item1-tab">
    <%= render 'plot', user: @user %>
  </div>
  <div class="tab-pane fade" id="item2" role="tabpanel" aria-labelledby="item2-tab">
    <%= render 'like', user: @user %>
  </div>
  <div class="tab-pane fade" id="item3" role="tabpanel" aria-labelledby="item3-tab">
    <%= render 'relationships/index', user: @user %>
  </div>
  <div class="tab-pane fade" id="item4" role="tabpanel" aria-labelledby="item4-tab">
    <%= render 'relationships/show', user: @user %>
  </div>
</div>